import json
import streamlit.components.v1 as components

def network_canvas(nodes, edges, results=None, height=610):
    p,q,_,_=results if results else ({},{},{},{})
    payload=json.dumps({'nodes':nodes,'edges':edges,'p':p,'q':q}).replace('</','<\\/')
    html='''<!doctype html><html><head><style>
body{margin:0;background:#0e1117;color:#fafafa;font:13px system-ui}.bar{padding:8px 12px;border-bottom:1px solid #333}.canvas{position:relative;height:550px;overflow:auto;background-image:radial-gradient(#30343b 1px,transparent 1px);background-size:20px 20px}.node{position:absolute;width:150px;padding:10px;border:1px solid #666;border-radius:8px;background:#171b22;box-shadow:0 2px 8px #0008;cursor:move;z-index:2}.kind{font-size:10px;text-transform:uppercase;opacity:.65}.res{margin-top:5px;color:#8dd3ff}.port{position:absolute;width:10px;height:10px;border-radius:50%;background:#ddd;top:34px}.in{left:-6px}.out{right:-6px}svg{position:absolute;inset:0;z-index:1;pointer-events:none}.edgeLabel{font-size:10px;fill:#ddd}.hint{opacity:.7}
</style></head><body><div class="bar"><b>FieldNet Engineering Canvas</b> <span class="hint">— drag equipment to arrange • typed ports shown • coordinates persist in exported case after using Auto-layout/position fields</span></div><div id="c" class="canvas"><svg id="s"></svg></div><script>
const D=__DATA__, c=document.getElementById('c'), s=document.getElementById('s'); const els={};
function pos(n,i){return [Number(n.x)||40+(i%4)*220,Number(n.y)||40+Math.floor(i/4)*120]}
D.nodes.forEach((n,i)=>{let [x,y]=pos(n,i),e=document.createElement('div');e.className='node';e.style.left=x+'px';e.style.top=y+'px';e.dataset.id=n.id;e.innerHTML=`<div class=kind>${n.kind}</div><b>${n.name}</b><i class="port in"></i><i class="port out"></i><div class=res>${D.p[n.id]!=null?D.p[n.id].toFixed(1)+' bar':'unsolved'}</div>`;c.appendChild(e);els[n.id]=e;let ox,oy,mx,my;e.onpointerdown=ev=>{e.setPointerCapture(ev.pointerId);ox=parseFloat(e.style.left);oy=parseFloat(e.style.top);mx=ev.clientX;my=ev.clientY};e.onpointermove=ev=>{if(!e.hasPointerCapture(ev.pointerId))return;e.style.left=ox+ev.clientX-mx+'px';e.style.top=oy+ev.clientY-my+'px';draw()};e.onpointerup=ev=>e.releasePointerCapture(ev.pointerId)});
function draw(){s.innerHTML='';let W=c.scrollWidth,H=c.scrollHeight;s.setAttribute('width',W);s.setAttribute('height',H);D.edges.forEach(ed=>{let a=els[ed.source],b=els[ed.target];if(!a||!b)return;let x1=a.offsetLeft+a.offsetWidth,y1=a.offsetTop+38,x2=b.offsetLeft,y2=b.offsetTop+38;let line=document.createElementNS('http://www.w3.org/2000/svg','path');let dx=Math.max(50,(x2-x1)/2);line.setAttribute('d',`M${x1},${y1} C${x1+dx},${y1} ${x2-dx},${y2} ${x2},${y2}`);line.setAttribute('stroke','#91a7ff');line.setAttribute('stroke-width','2');line.setAttribute('fill','none');s.appendChild(line);let t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',(x1+x2)/2);t.setAttribute('y',(y1+y2)/2-5);t.setAttribute('class','edgeLabel');t.textContent=ed.kind+(D.q[ed.id]!=null?' • '+D.q[ed.id].toFixed(0)+' m³/d':'');s.appendChild(t)})} draw();
</script></body></html>'''.replace('__DATA__',payload)
    components.html(html,height=height,scrolling=False)
